database:
  driverClass: com.mysql.jdbc.Driver
  user: myuser
  password: xxxx
  url: jdbc:mysql://localhost:3306/playlistdb

server: 
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  rootPath: /
logging:
  level: INFO
  loggers:
    chris: DEBUG
